# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'todo-app'
    publishLocation: 'Container'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'todo-app-server'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**'
    targetFolder: '/var/todoapp'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'todo-app-server'
    runOptions: 'commands'
    commands: 'sudo java -jar  /var/todoapp/todo-app-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &'
    readyTimeout: '20000'

